@WebApi_HostAddress = http://localhost:5078

GET {{WebApi_HostAddress}}/weatherforecast/
Accept: application/json

###

POST {{WebApi_HostAddress}}/api/shorturl/
Content-Type: application/json
{
  "url": "https://www.example.com",
  "DteId": "Dte123456"
}

###

GET {{WebApi_HostAddress}}/api/ShortUrl


###

GET {{WebApi_HostAddress}}/api/ShortUrl/9777ffc8