@WebApi_HostAddress = http://localhost:5078


POST {{WebApi_HostAddress}}/api/shorturl/
Content-Type: application/json
{
  "url": "https://www.example.com",
  "DteId": "2"
}

###

POST {{WebApi_HostAddress}}/api/shorturl/
Content-Type: application/json
{
  "url": "https://www.example.com",
  "DteId": "DteDoestExist12345"
}

###

GET {{WebApi_HostAddress}}/api/ShortUrl


###

GET {{WebApi_HostAddress}}/api/ShortUrl/60f63b30

###

POST {{WebApi_HostAddress}}/api/auth/login
Content-Type: application/json

{
  "username": "admin",
  "password": "admin123"
}